python test-transformer.py --task conversion \
                           --data-path-parent /groups/MotionPred/motion-inference/full-body-special-sets \
                           --figure-file-path ./posture-images/full-body/transformer-enc-histogram-special-test.pdf \
                           --model-dir ./models/motion-inference/full-body/transformer-enc \
                           --representation quaternions \
                           --batch-size=512 \
                           --seq-length=30 \
                           --downsample=6 \
                           --stride=30 \
                           --num-heads=4 \
                           --dim-feedforward=200 \
                           --dropout=0.0 \
                           --num-layers=2
