python test-transformer.py --task conversion \
                           --data-path-parent "/home/jackg7/VT-Natural-Motion-Processing/data" \
                           --figure-file-path "/home/jackg7/VT-Natural-Motion-Processing/images/transformer-test.pdf" \
                           --figure-title "Seq2Seq" \
                           --model-dir "/home/jackg7/VT-Natural-Motion-Processing/models/set-2" \
                           --full-transformer \
                           --representation quaternions \
                           --batch-size=512 \
                           --seq-length=30 \
                           --downsample=6 \
                           --in-out-ratio=1 \
                           --stride=30 \
                           --num-heads=4 \
                           --dim-feedforward=512 \
                           --dropout=0.0 \
                           --num-layers=2
