python train-seq2seq.py --task prediction \
                        --data-path /groups/MotionPred/motion-prediction/full-set \
                        --model-file-path ./models/motion-prediction/seq2seq-dot-birnn-full-set.pt \
                        --norm-quaternions \
                        --batch-size=32 \
                        --seq-length=240 \
                        --downsample=6 \
                        --stride=240 \
                        --learning-rate=0.001 \
                        --num-epochs=5 \
                        --hidden-size=512 \
                        --attention=dot \
                        --bidirectional
