python train-transformer.py --task conversion \
                            --data-path test-folder \
                            --representation quaternions \
                            --model-file-path model.pt \
                            --full-transformer \
                            --batch-size=32 \
                            --seq-length=30 \
                            --downsample=6 \
                            --stride=30 \
                            --learning-rate=0.001 \
                            --beta-one=0.95 \
                            --beta-two=0.999 \
                            --num-epochs=5 \
                            --num-heads=4 \
                            --dim-feedforward=200 \
                            --dropout=0.0 \
                            --num-layers=2
