python train-seq2seq.py --task conversion \
                        --data-path test-folder \
                        --model-file-path model.pt \
                        --representation quaternions \
                        --batch-size=32 \
                        --seq-length=30 \
                        --downsample=6 \
                        --stride=30 \
                        --learning-rate=0.001 \
                        --num-epochs=5 \
                        --hidden-size=512 \
                        --attention=dot \
                        --bidirectional
